// Generated by gencpp from file ble_device_scanner/DeviceTuple.msg
// DO NOT EDIT!


#ifndef BLE_DEVICE_SCANNER_MESSAGE_DEVICETUPLE_H
#define BLE_DEVICE_SCANNER_MESSAGE_DEVICETUPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ble_device_scanner
{
template <class ContainerAllocator>
struct DeviceTuple_
{
  typedef DeviceTuple_<ContainerAllocator> Type;

  DeviceTuple_()
    : adtype()
    , description()
    , value()  {
    }
  DeviceTuple_(const ContainerAllocator& _alloc)
    : adtype(_alloc)
    , description(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _adtype_type;
  _adtype_type adtype;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceTuple_

typedef ::ble_device_scanner::DeviceTuple_<std::allocator<void> > DeviceTuple;

typedef boost::shared_ptr< ::ble_device_scanner::DeviceTuple > DeviceTuplePtr;
typedef boost::shared_ptr< ::ble_device_scanner::DeviceTuple const> DeviceTupleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ble_device_scanner::DeviceTuple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ble_device_scanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ble_device_scanner': ['/home/pieter/turtlebot_ws/src/ble_device_scanner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95ad3a1e30c3e0f92aabbef8049d4259";
  }

  static const char* value(const ::ble_device_scanner::DeviceTuple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95ad3a1e30c3e0f9ULL;
  static const uint64_t static_value2 = 0x2aabbef8049d4259ULL;
};

template<class ContainerAllocator>
struct DataType< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ble_device_scanner/DeviceTuple";
  }

  static const char* value(const ::ble_device_scanner::DeviceTuple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string adtype\n\
string description\n\
string value\n\
";
  }

  static const char* value(const ::ble_device_scanner::DeviceTuple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.adtype);
      stream.next(m.description);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceTuple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ble_device_scanner::DeviceTuple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ble_device_scanner::DeviceTuple_<ContainerAllocator>& v)
  {
    s << indent << "adtype: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.adtype);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLE_DEVICE_SCANNER_MESSAGE_DEVICETUPLE_H
