// Generated by gencpp from file ble_device_scanner/Devices.msg
// DO NOT EDIT!


#ifndef BLE_DEVICE_SCANNER_MESSAGE_DEVICES_H
#define BLE_DEVICE_SCANNER_MESSAGE_DEVICES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ble_device_scanner/Device.h>

namespace ble_device_scanner
{
template <class ContainerAllocator>
struct Devices_
{
  typedef Devices_<ContainerAllocator> Type;

  Devices_()
    : devices()  {
    }
  Devices_(const ContainerAllocator& _alloc)
    : devices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ble_device_scanner::Device_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ble_device_scanner::Device_<ContainerAllocator> >::other >  _devices_type;
  _devices_type devices;





  typedef boost::shared_ptr< ::ble_device_scanner::Devices_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ble_device_scanner::Devices_<ContainerAllocator> const> ConstPtr;

}; // struct Devices_

typedef ::ble_device_scanner::Devices_<std::allocator<void> > Devices;

typedef boost::shared_ptr< ::ble_device_scanner::Devices > DevicesPtr;
typedef boost::shared_ptr< ::ble_device_scanner::Devices const> DevicesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ble_device_scanner::Devices_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ble_device_scanner::Devices_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ble_device_scanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ble_device_scanner': ['/home/pieter/turtlebot_ws/src/ble_device_scanner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ble_device_scanner::Devices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ble_device_scanner::Devices_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_device_scanner::Devices_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_device_scanner::Devices_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_device_scanner::Devices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_device_scanner::Devices_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ble_device_scanner::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6b9a7c347baec7197f38a109b072f06";
  }

  static const char* value(const ::ble_device_scanner::Devices_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6b9a7c347baec71ULL;
  static const uint64_t static_value2 = 0x97f38a109b072f06ULL;
};

template<class ContainerAllocator>
struct DataType< ::ble_device_scanner::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ble_device_scanner/Devices";
  }

  static const char* value(const ::ble_device_scanner::Devices_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ble_device_scanner::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ble_device_scanner/Device[] devices\n\
================================================================================\n\
MSG: ble_device_scanner/Device\n\
string rssi\n\
string addr\n\
ble_device_scanner/DeviceTuple[] data\n\
\n\
================================================================================\n\
MSG: ble_device_scanner/DeviceTuple\n\
string adtype\n\
string description\n\
string value\n\
";
  }

  static const char* value(const ::ble_device_scanner::Devices_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ble_device_scanner::Devices_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Devices_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ble_device_scanner::Devices_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ble_device_scanner::Devices_<ContainerAllocator>& v)
  {
    s << indent << "devices[]" << std::endl;
    for (size_t i = 0; i < v.devices.size(); ++i)
    {
      s << indent << "  devices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ble_device_scanner::Device_<ContainerAllocator> >::stream(s, indent + "    ", v.devices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLE_DEVICE_SCANNER_MESSAGE_DEVICES_H
